name: PlunziChatPlugin
version: '6.9-420-UwU'
main: sh.plunzi.plunzichatplugin.PlunziChatPlugin
api-version: 1.18
authors: [ Monsbot ]
description: The chat plugin for the Plunzish Minecraft server (enables use of Pixmojis)
commands:
  msg:
    description: Privately Message a player
    aliases: [ w, tell, dm ]
  broadcast:
    description: Broadcast a message to the entire server
    aliases: [ yellatthewholeserver ]
  debug:
     description: debug
     aliases: [ deez, nuts ]
  setcensor:
    description: setcensor [heavy, light, none]
  op:
    description: /op <player>
  deop:
    description: /deop <player>
  clearmydata:
      description: clears your data from the database
  friends:
    description: /friends [add/remove] <player> | /friends (/friend also works in both cases)
    aliases: [ friend, fr ]
  color:
    description: /color [#color1] [#color2] <message>
  t:
    description: Send a message just like in chat. Shows you what pixmojis and @s you can use (works in console too)
  r:
    description: Respond to the last private message somebody sent you