name: PlunziChatPlugin
version: '${project.version}'
main: sh.plunzi.plunzichatplugin.PlunziChatPlugin
api-version: 1.18
authors: [ Monsbot ]
description: The chat plugin for the Plunzish Minecraft server (enables use of Pixmojis)
